// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/tabbed/pqtype"
)

type Post struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	ShopID          int64          `json:"shop_id"`
	CoverImage      sql.NullString `json:"cover_image"`
	Images          []string       `json:"images"`
	PostTitle       sql.NullString `json:"post_title"`
	SellingAddress  sql.NullString `json:"selling_address"`
	SellingCity     sql.NullString `json:"selling_city"`
	SellingDistrict sql.NullString `json:"selling_district"`
	SellingWard     sql.NullString `json:"selling_ward"`
	CityCode        sql.NullInt32  `json:"city_code"`
	DistrictCode    sql.NullInt32  `json:"district_code"`
	WardCode        sql.NullInt32  `json:"ward_code"`
	Price           int32          `json:"price"`
	PostCategoryID  int64          `json:"post_category_id"`
	PostContent     sql.NullString `json:"post_content"`
	PostNote        sql.NullString `json:"post_note"`
	TotalView       sql.NullInt32  `json:"total_view"`
	// time, notime
	PostType       string       `json:"post_type"`
	ExpirationDate sql.NullTime `json:"expiration_date"`
	// active, unactive, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostCategory struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// active, unactive, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostChangeHistory struct {
	ID         int64          `json:"id"`
	PostID     int64          `json:"post_id"`
	UserID     int64          `json:"user_id"`
	OldContent sql.NullString `json:"old_content"`
	NewContent sql.NullString `json:"new_content"`
	OldNote    sql.NullString `json:"old_note"`
	NewNote    sql.NullString `json:"new_note"`
	// active, unactive, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostComment struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	PostID         int64          `json:"post_id"`
	CommentContent sql.NullString `json:"comment_content"`
	StarRating     sql.NullInt32  `json:"star_rating"`
	// active, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostReplyComment struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	PostID         int64  `json:"post_id"`
	PostCommentID  int64  `json:"post_comment_id"`
	CommentContent string `json:"comment_content"`
	// active, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostReport struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// active, unactive, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostsPostReport struct {
	ID           int64        `json:"id"`
	UserID       int64        `json:"user_id"`
	PostID       int64        `json:"post_id"`
	PostReportID int64        `json:"post_report_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type PostsSaved struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	PostID    int64        `json:"post_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Shop struct {
	ID             int64          `json:"id"`
	OwnerID        int64          `json:"owner_id"`
	ShopName       string         `json:"shop_name"`
	ShopAddress    sql.NullString `json:"shop_address"`
	CoverImage     sql.NullString `json:"cover_image"`
	Avatar         sql.NullString `json:"avatar"`
	ShopPhone      sql.NullString `json:"shop_phone"`
	Description    sql.NullString `json:"description"`
	TotalView      sql.NullInt32  `json:"total_view"`
	ShopCategoryID int64          `json:"shop_category_id"`
	// [{social:"facebook",url:"https://facebook.com"}]
	Socials pqtype.NullRawMessage `json:"socials"`
	// active, unactive, delete
	Status string `json:"status"`
	// normal, stop
	AdminStatus       string       `json:"admin_status"`
	ShopnameChangedAt time.Time    `json:"shopname_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type ShopCategory struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// active, unactive, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ShopMember struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"member_id"`
	ShopID   int64 `json:"shop_id"`
	// view, edit
	MemberRole string `json:"member_role"`
	// active, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ShopReport struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// active, unactive, delete
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ShopsShopReport struct {
	ID           int64        `json:"id"`
	UserID       int64        `json:"user_id"`
	ShopID       int64        `json:"shop_id"`
	ShopReportID int64        `json:"shop_report_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type User struct {
	ID                int64          `json:"id"`
	FullName          string         `json:"full_name"`
	Avatar            sql.NullString `json:"avatar"`
	Email             string         `json:"email"`
	Phone             string         `json:"phone"`
	HashedPassword    string         `json:"hashed_password"`
	UserRole          string         `json:"user_role"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}
